name: scheduler_app_sms
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  font_awesome_flutter: 10.7.0
  shared_preferences: 2.3.1
  firebase_core: 3.3.0
  firebase_auth: 5.1.4
  cloud_firestore: 5.2.1
  firebase_storage: 12.1.3
  flutter_slidable: ^3.1.1
  onboarding: ^4.0.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_smart_dialog: ^4.9.8
  intl: ^0.19.0
  flutter_datetime_picker_plus: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/fonts/
    - assets/fonts/Rubik/
    - assets/icon/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
fonts:
  - family: rubik
    fonts:
      - asset: assets/fonts/Rubik/Rubik-Light.ttf
        weight: 300
      - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        weight: 400
      - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        weight: 500
      - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        weight: 700
      - asset: assets/fonts/Rubik/Rubik-Black.ttf
        weight: 900
